/*
 * generated by Xtext
 */
package org.xtext.example.entity.ui.contentassist

import org.xtext.example.entity.ui.contentassist.AbstractEntityDSLProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class EntityDSLProposalProvider extends AbstractEntityDSLProposalProvider {
}
