<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="diagram" nsURI="http://www.zafinlabs.com/mirev/jewel/dsl/diagram/model/Diagram"
    nsPrefix="diagram">
  <eClassifiers xsi:type="ecore:EClass" name="Diagram">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dNamespaces" upperBound="-1"
        eType="#//DNamespace" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DNamespace">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//DNamespace"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dEntities" upperBound="-1"
        eType="#//DEntity" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DEntity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" eType="ecore:EClass ../../org.xtext.example.entity/model/generated/EntityDSL.ecore#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//DEntity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TPort" eType="#//DPort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="BPort" eType="#//DPort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DPort"/>
</ecore:EPackage>
