/*
 * generated by Xtext
 */
package org.xtext.example.entity.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.example.entity.ui.internal.EntityDSLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class EntityDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return EntityDSLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return EntityDSLActivator.getInstance().getInjector(EntityDSLActivator.ORG_XTEXT_EXAMPLE_ENTITY_ENTITYDSL);
	}
	
}
