/*
 * generated by Xtext
 */
package org.xtext.example.entity.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class EntityDSLUiModule extends org.xtext.example.entity.ui.AbstractEntityDSLUiModule {
	public EntityDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
