/*
* generated by Xtext
*/
package org.xtext.example.entity;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class EntityDSLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.xtext.example.entity.ui.internal.EntityDSLActivator.getInstance().getInjector("org.xtext.example.entity.EntityDSL");
	}
	
}
