/*
 * generated by Xtext
 */
package org.xtext.example.entity;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EntityDSLRuntimeModule extends org.xtext.example.entity.AbstractEntityDSLRuntimeModule {

}
