/*
* generated by Xtext
*/
package org.xtext.example.entity;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class EntityDSLStandaloneSetup extends EntityDSLStandaloneSetupGenerated{

	public static void doSetup() {
		new EntityDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

