/*
* generated by Xtext
*/
package org.xtext.example.entity.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.entity.services.EntityDSLGrammarAccess;

public class EntityDSLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private EntityDSLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.example.entity.parser.antlr.internal.InternalEntityDSLParser createParser(XtextTokenStream stream) {
		return new org.xtext.example.entity.parser.antlr.internal.InternalEntityDSLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "NamespaceDefinition";
	}
	
	public EntityDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(EntityDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
